# Generated by Django 6.0.5 on 2026-05-11 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CertificateLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=100, verbose_name='操作')),
                ('detail', models.TextField(blank=True, verbose_name='详情')),
                ('operator', models.CharField(blank=True, max_length=100, verbose_name='操作人')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='时间')),
            ],
            options={
                'verbose_name': '证明流程日志',
                'verbose_name_plural': '证明流程日志',
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CertificateMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='材料名称')),
                ('detail', models.TextField(blank=True, verbose_name='材料说明')),
                ('is_required', models.BooleanField(default=True, verbose_name='是否必填')),
                ('is_valid', models.BooleanField(default=False, verbose_name='是否通过校验')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '证明材料',
                'verbose_name_plural': '证明材料',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='CertificateRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_no', models.CharField(max_length=40, unique=True, verbose_name='申请单号')),
                ('cert_type', models.CharField(max_length=100, verbose_name='证明类型')),
                ('purpose', models.TextField(blank=True, verbose_name='用途说明')),
                ('attachment_note', models.TextField(blank=True, verbose_name='补充材料说明')),
                ('status', models.CharField(choices=[('draft', '待提交'), ('material_pending', '待材料校验'), ('material_rejected', '待补充材料'), ('pending_review', '待管理员处理'), ('rejected', '审批驳回'), ('approved_observing', '24小时观察期'), ('revoked', '已撤回作废'), ('completed', '已办结')], default='draft', max_length=32, verbose_name='状态')),
                ('rejection_reason', models.TextField(blank=True, verbose_name='驳回意见')),
                ('generated_pdf', models.FileField(blank=True, null=True, upload_to='certificates/', verbose_name='生成文件')),
                ('is_pdf_void', models.BooleanField(default=False, verbose_name='PDF是否作废')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='提交时间')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='审批通过时间')),
                ('revoke_deadline', models.DateTimeField(blank=True, null=True, verbose_name='撤回截止时间')),
                ('revoked_at', models.DateTimeField(blank=True, null=True, verbose_name='撤回时间')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='办结时间')),
                ('last_operator', models.CharField(blank=True, max_length=100, verbose_name='最近操作人')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '证明申请',
                'verbose_name_plural': '证明申请',
                'ordering': ['-updated_at', '-created_at'],
            },
        ),
    ]
